### ISSUE TITLE
how is the calculation formula of the kernel_values obtained

### ISSUE THREAD

**Issue by MengtingXu1203** [connorlee77/pytorch-mutual-information#2]
Hello, I would like to ask, when calculating the marginalPdf, how is the calculation formula of the kernel_values obtained, why the value of sigma is 2*0.4**2, is there any reference material？

**Comment by connorlee77** [comment]
Ahh good catch, this seems like a repeated calculation as the $2 \sigma ^ 2$ operation is already being done in 
```
kernel_values = torch.exp(-0.5*(residuals / self.sigma).pow(2))
```
