### ISSUE TITLE
Take a look at the error msg.

### ISSUE THREAD

**Issue by redLinmumu** [connorlee77/pytorch-mutual-information#4]
MutualInformation.py", line 14, in __init__
    self.bins = nn.Parameter(torch.linspace(0, 255, num_bins, device=device).float(), requires_grad=False)
NameError: name 'device' is not defined

**Comment by huynhtuan17ti** [comment]
You can specify a global variable `device=...`.

**Comment by connorlee77** [comment]
Nice catch! Fixed.
